import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Images Uploader",
  description: "Generated by Facundo Fernandez",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-gray-100"
    >
      <body
        className={`h-screen flex flex-col justify-between items-center ${inter.className}`}
      >
        {children}

        <footer className="flex justify-center mb-3">
          <p className="font-medium text-sm text-center text-gray-400">
            Created by{" "}
            <span className="font-semibold underline">Facundo Fernandez</span> -
            devChallenges.io
          </p>
        </footer>
      </body>
    </html>
  );
}
